server:
  port: ${port:8881}


xxl:
  job:
    admin:
      addresses: http://192.168.200.130:8888/xxl-job-admin  #xxl_job 服务器地址
    executor:
      appname: simple-xxl-job-executor  #执行器也是集群配置
      port: ${executor.port:9991}  #服务器回调端口
